services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    env_file:
      - .localstack.env
    environment:
      SERVICES: s3,sqs,dynamodb,iam